task_name: Pipeline8_Test0902_1k

vlm:
    model_name: llava16_cli     # [llava16_cli | chatgpt]
    llava_model_base_dir: null  # null is read as None
    llava_model_dir: ../llm_models/llava/llava-v1.6-34b     # ignored if chatgpt is a model
llm:
    model_name: meta-llama/Meta-Llama-3-8B-Instruct
    # model_name: meta-llama/Meta-Llama-3-70B-Instruct
    # model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
    use_summary: False
    use_decision: False
gpt:
    model_name: gpt-4o-mini-2024-07-18
    use_summary: False
    use_decision: False
    seed: 17
    temperature: 0.2
    api_key: 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

prompt_lib_name: Baseline_single_turn

yolo:
    dynamic_det_path: yolo/WEIGHTS/aihub_pwalk/train852/weights/best.pt
    static_det_path: yolo/WEIGHTS/gd_demo/train958/weights/best.pt
    use_det_info: False

depth_anything:
    encoder: vitl
    dataset: vkitti
    max_depth: 80       # meter

image_server:
    path: /media/NAS_GDHRI/dbs/aihub_pwalk/organized/JPEGImages # 이미지 파일들이 있는 Server 폴더 경로
    copy_to_db_images: True
    n_images: 20000
    ref_path: /home/yochin/Desktop/PathGuidedVQA_Base/output/(2024.08.05)DestMasking_DrawPoint_NoExample_DecGPT_SumLLama38binst_DBvalMore4k/original_images

db:
    base_dir: /home/yochin/Desktop/PathGuidedVQA_Base/test1k_0902/organized
    images: original_images
    depths: depth_anything_v2
    det_anno_pred: det_anno_pred
    det_anno_gt: det_anno_gt
    paths: paths
    gp_info: gp_info_xml
    gt: desc_gt_en

use_org_image: True     # True means No Masks

dest:
    masking_depth: False
    depth_meter: 5.0
    masking_circle: False
    circle_ratio_w: 0.1
    draw_circle: False
    draw_point: False   # prompt_libray, cahnge prompt circle to point
    draw_bbox: False    # False only
    use_path_mask: True

output_dir: /home/yochin/Desktop/PathGuidedVQA_Base/output/2024.09.02

gp:
    method: load_xml    # [load_xml | load_anno | select_det | set_front], if all methods are failed, set_front is the last.
    # This is temporary for testing algorithm
    method_set_front_type: ten_meters_from_below_point   # [manual | three_quarters | ten_meters_from_below_point | ten_meters_from_depth]
    max_search_degree: 45   # >= 0, int
    np_rnd_seed: 17

local_path_planning: line  # [depth_lpp | line]

apply_cam_intrinsic: True

